name: MuseTalk
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pytorch-cuda=11.8
  - pip
  - pip:
    - diffusers==0.30.2
    - accelerate==0.28.0
    - numpy==1.23.5
    - tensorflow==2.12.0
    - tensorboard==2.12.0
    - opencv-python==4.9.0.80
    - soundfile==0.12.1
    - transformers==4.39.2
    - huggingface_hub==0.30.2
    - librosa==0.11.0
    - einops==0.8.1
    - gradio==5.24.0
    - gdown
    - requests
    - imageio[ffmpeg]
    - omegaconf
    - ffmpeg-python
    - moviepy
    - openmim
    - mmengine
    - mmcv==2.0.1
    - mmdet==3.1.0
    - mmpose==1.1.0